<?php
	//define('URL', __DIR__.'/../'); //Folosita in cod PHP ...
	define('URLP', 'D:/wamp/www/Catalog_v3/'); //Folosita in cod PHP ...
	define('URLH', 'http://localhost/Catalog_v3/'); //Used in cod HTML ...
	